function [xyz, g] = ll2xyz_with_gradient(lon_lat)
xyz = [cosd(lon_lat(:, 2)) .* cosd(lon_lat(:, 1)), ...
    cosd(lon_lat(:, 2)) .* sind(lon_lat(:, 1)), ...
    sind(lon_lat(:, 2))];

m = size(lon_lat, 1);
g1 = [-cosd(lon_lat(:, 2)) .* sind(lon_lat(:, 1)), ...
    cosd(lon_lat(:, 2)) .* cosd(lon_lat(:, 1)), ...
    zeros(m, 1)];  % size m*3
g2 = [-sind(lon_lat(:, 2)) .* cosd(lon_lat(:, 1)), ...
    -sind(lon_lat(:, 2)) .* sind(lon_lat(:, 1)), ...
    cosd(lon_lat(:, 2))];  % size m*3
g = cat(3, g1, g2) * pi / 180;  % size m*3*2
g = permute(g, [2, 3, 1]);
end